#!/bin/bash

for arg in "${@:1}"; do
    if [ -z "$files_to_delete" ]; then
        files_to_delete="\"$(pwd)/$arg\""
    else
        files_to_delete="$files_to_delete, \"$(pwd)/$arg\""
    fi
done

osascript <<EOD
    set POSIX_files_to_delete to { $files_to_delete }
    set files_to_delete to {}
    tell app "Finder"
        repeat with POSIX_path in POSIX_files_to_delete
            set end of files_to_delete to (POSIX_path as POSIX file)
        end repeat
        delete files_to_delete
    end tell
EOD
